networks:
  - main
  - isolated

parameters:
  db.login: root
  db.password: 12345

services:
  component.db_default:
    network: main
    class: \Examples\Request
    parameters:
      - '%db.login'
      - '%db.password'
      - '@component.db_alt'


  component.db_alt:
    network: isolated
    class: \Examples\Request2
    parameters:
      - '%db.login'
      - '%db.password'

