networks:
  - main

parameters:
  db.login: root
  db.password: 12345

services:
  component.db_default:
    network: main
    class: \Carpenstar\Examples\ExampleObject1
    parameters:
      - '%db.login'
      - '%db.password'
      - '@component.db_alt'


  component.db_alt:
    network: main
    class: \Carpenstar\Examples\ExampleObject2
    parameters:
      - '%db.login'
      - '%db.password'

